launcher_args: {experiment_name: graff_ms_baseline_canopus_train_public,
  script_name: "src/ms_pred/graff_ms/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [3],
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, 
    nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [64]
  max-epochs: [200]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv] 

  learning-rate: [0.00018]
  lr-decay-rate: [0.92]
  num-bins: [15000] 
  loss-fn: [cosine]

  dropout: [0.3]
  hidden-size: [512]
  layers: [6]
  weight-decay: [1e-6]
  pe-embed-k: [11]
  pool-op: [avg]
  set-layers: [0]
  use-reverse: [false]

  form-dir-name: ['magma_subform_50_with_raw']
  embed-adduct: [true]
  mpnn-type: [GGNN]
  num-fixed-forms: [5000]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1]
