launcher_args: {experiment_name: molnetms_baseline_nist20,
  script_name: "src/ms_pred/molnetms/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [2],
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, 
    nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [16]
  max-epochs: [200]

  dataset-name: [nist20]
  split-name: [split_1.tsv] 

  learning-rate: [0.00073]
  lr-decay-rate: [0.855]
  num-bins: [15000] 
  loss-fn: [cosine]

  dropout: [0.3]
  hidden-size: [256]
  layers: [2]
  top-layers: [2]
  neighbors: [5]
  use-reverse: [false]
  weight-decay: [1e-6]

  form-dir-name: ['no_subform']
  embed-adduct: [true]

iterative_args:
  #-  split-name: [split_1.tsv]
  #   save-dir: [split_1]
  -  split-name: [scaffold_1.tsv]
     save-dir: [scaffold_1]
