launcher_args: {experiment_name: gnn_baseline_nist20,
  script_name: "src/ms_pred/gnn_pred/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [2],
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, 
     nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [64]
  max-epochs: [200]

  dataset-name: [nist20]
  split-name: [split_1.tsv] 

  learning-rate: [0.00052]
  lr-decay-rate: [0.767]
  num-bins: [15000] 
  loss-fn: [cosine]

  dropout: [0.0]
  mpnn-type: [GGNN]
  pe-embed-k: [19]
  pool-op: [avg]
  set-layers: [0]
  hidden-size: [512]
  use-reverse: [true]
  weight-decay: [1e-7]
  layers: [4]

  form-dir-name: ['no_subform']
  embed-adduct: [true]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     seed: [1]

  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd2]
     seed: [2]

  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd3]
     seed: [3]

  -  split-name: [scaffold_1.tsv]
     save-dir: [scaffold_1]
