launcher_args: {experiment_name: ffn_baseline_nist20,
  script_name: "src/ms_pred/ffn_pred/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [1]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G,
    time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [128]
  max-epochs: [200]

  dataset-name: [nist20]
  split-name: [split_1.tsv]

  learning-rate: [0.00087]
  lr-decay-rate: [0.722]
  num-bins: [15000]
  loss-fn: [cosine]

  dropout: [0.0]
  hidden-size: [512]
  use-reverse: [true]
  weight-decay: [0]
  layers: [2]

  form-dir-name: ['no_subform']
  embed-adduct: [true]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1]
  -  split-name: [scaffold_1.tsv]
     save-dir: [scaffold_1]
