launcher_args: {experiment_name: scarf_gf_inten_canopus_train_public,
  script_name: "src/ms_pred/scarf_pred/train_inten.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [10] #[20]
  batch-size: [32]
  max-epochs: [200]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv] #[split_1.tsv, split_2.tsv, split_3.tsv]

  learning-rate: [0.00015] # moved down
  lr-decay-rate: [0.962]

  root-embedder: [graphormer] # gnn

  dropout: [0.2]
  mpnn-type: [GGNN]
  pe-embed-k: [7]
  pool-op: [attn]
  hidden-size: [512] #128
  weight-decay: [0]
  set-layers: [0]
  form-set-layers: [2] #[1]
  mlp-layers: [2]
  gnn-layers: [3]
  embedder: [abs-sines]
  binned-targs: [true] 
  no-mol: [false]
  info-join: [concat]
  loss-fn: [cosine]
  embed-adduct: [true]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1]
     formula-folder: [results/scarf_canopus_train_public/split_1/preds_train_300_inten/]

  #-  split-name: [hyperopt.tsv]
  #   save-dir: [hyperopt]
  #   formula-folder: [results/scarf_nist_hyperopt_adduct_mol/hyperopt/preds_train_300_inten/]
